const $ = id => document.getElementById(id);
const canvas = $('view');
const gl = canvas.getContext('webgl', {antialias:true, preserveDrawingBuffer:true});
let yaw=0.65, elevation=0.82, distance=205, dragging=false, last=[0,0], mesh, count=0;
function shader(type, source) {const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function program() {const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,`
attribute vec3 position; attribute vec3 normal;
uniform vec3 right; uniform vec3 up; uniform vec3 back; uniform float distance; uniform mat4 projection;
varying vec3 n; varying vec3 world;
void main(){n=normal;world=position;vec3 q=vec3(dot(position,right),dot(position,up),dot(position,back)-distance);gl_Position=projection*vec4(q,1.0);}`));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,`
precision highp float;varying vec3 n;varying vec3 world;uniform bool lines;
void main(){if(lines){gl_FragColor=vec4(0.12,0.17,0.12,1.0);return;}vec3 N=normalize(n);float light=max(dot(N,normalize(vec3(-0.5,-0.7,1.0))),0.0);float rim=max(dot(N,normalize(vec3(0.7,0.5,0.3))),0.0);vec3 base=vec3(0.66,0.73,0.47);vec3 color=base*(0.28+0.68*light)+vec3(0.20,0.27,0.25)*rim;gl_FragColor=vec4(color,1.0);}`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
try {
 if(!gl)throw Error('WebGL is unavailable in this browser.');
 const response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build the WASM module first: ./scripts/build-web.sh');
 const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{});const kernel=instance.exports;
 const p=program();gl.useProgram(p);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
 const locations=Object.fromEntries(['right','up','back','distance','projection','lines'].map(k=>[k,gl.getUniformLocation(p,k)]));
 const positions=gl.createBuffer(), normals=gl.createBuffer(), linePositions=gl.createBuffer(), lineNormals=gl.createBuffer();
 function bind(buffer,attribute,data){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);if(data)gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);const loc=gl.getAttribLocation(p,attribute);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);}
 function generate(){const radius=Number($('radius').value);const preset=Number($('preset').value);const status=kernel.hagane_generate_preset(preset,radius,0.05);const text=new TextDecoder().decode(new Uint8Array(kernel.memory.buffer,kernel.hagane_output_ptr(),kernel.hagane_output_len()));mesh=JSON.parse(text);if(status)throw Error(mesh.error);count=mesh.positions.length/3;bind(positions,'position',mesh.positions);bind(normals,'normal',mesh.normals);const lines=[],ns=[];for(let i=0;i<count;i+=3){for(const [a,b] of [[0,1],[1,2],[2,0]]){lines.push(...mesh.positions.slice((i+a)*3,(i+a+1)*3),...mesh.positions.slice((i+b)*3,(i+b+1)*3));ns.push(...mesh.normals.slice((i+a)*3,(i+a+1)*3),...mesh.normals.slice((i+b)*3,(i+b+1)*3));}}bind(linePositions,'position',lines);bind(lineNormals,'normal',ns);const names=['Through bore','Four through bores','L-profile extrusion','Hollow tube'];const descriptions=['80 × 60 × 24 mm block','80 × 60 × 24 mm · four holes','Concave profile · polygon hole · skew extrusion','Ø60 mm outer · 24 mm height'];$('part-title').textContent=names[preset];$('part-description').textContent=descriptions[preset];$('radius').disabled=preset===2;$('radius-title').textContent=preset===3?'Inner radius':'Bore radius';$('radius-label').value=preset===2?'Fixed profile':(preset===1?radius*0.5:radius).toFixed(1)+' mm';$('topology').textContent=mesh.faces+' faces / '+mesh.edges+' edges';$('volume').textContent=mesh.volume.toLocaleString('en-US',{maximumFractionDigits:1})+' mm³';$('triangles').textContent=(count/3).toLocaleString('en-US');$('status').textContent='✓ Closed B-rep validated in Rust';window.haganeDemo.mesh=mesh;render();}
 function render(){const dpr=Math.min(devicePixelRatio,2);const w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const back=[Math.sin(yaw)*Math.cos(elevation),-Math.cos(yaw)*Math.cos(elevation),Math.sin(elevation)],right=[Math.cos(yaw),Math.sin(yaw),0],up=[-Math.sin(yaw)*Math.sin(elevation),Math.cos(yaw)*Math.sin(elevation),Math.cos(elevation)];gl.uniform3fv(locations.back,back);gl.uniform3fv(locations.right,right);gl.uniform3fv(locations.up,up);gl.uniform1f(locations.distance,distance);const f=1/Math.tan(0.65/2),near=1,far=1000;gl.uniformMatrix4fv(locations.projection,false,new Float32Array([f/(w/h),0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]));bind(positions,'position');bind(normals,'normal');gl.uniform1i(locations.lines,0);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);gl.drawArrays(gl.TRIANGLES,0,count);gl.disable(gl.POLYGON_OFFSET_FILL);if($('wire').checked){bind(linePositions,'position');bind(lineNormals,'normal');gl.uniform1i(locations.lines,1);gl.drawArrays(gl.LINES,0,count*2);}}
 window.haganeDemo={ready:false,setAngle(a){yaw=a;render();},render};
 $('preset').addEventListener('change',()=>{try{generate();}catch(e){$('status').textContent=e.message;}});$('radius').addEventListener('input' ,()=>{try{generate();}catch(e){$('status').textContent=e.message;}});$('wire').addEventListener('change',render);$('reset').addEventListener('click',()=>{yaw=0.65;elevation=0.82;distance=205;render();});
 canvas.addEventListener('pointerdown',e=>{dragging=true;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw+=(e.clientX-last[0])*0.008;elevation=Math.max(-1.35,Math.min(1.35,elevation+(e.clientY-last[1])*0.006));last=[e.clientX,e.clientY];render();});canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(120,Math.min(350,distance*Math.exp(e.deltaY*0.001)));render();},{passive:false});canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')yaw-=0.1;else if(e.key==='ArrowRight')yaw+=0.1;else if(e.key==='ArrowUp')elevation=Math.min(1.35,elevation+0.1);else if(e.key==='ArrowDown')elevation=Math.max(-1.35,elevation-0.1);else if(e.key==='+')distance=Math.max(120,distance-10);else if(e.key==='-')distance=Math.min(350,distance+10);else return;e.preventDefault();render();});new ResizeObserver(render).observe(canvas);
 let previous=performance.now();function frame(now){if($('spin').checked){yaw+=(now-previous)*0.00025;render();}previous=now;requestAnimationFrame(frame);}generate();window.haganeDemo.ready=true;requestAnimationFrame(frame);
} catch(e) {$('status').textContent=e.message;console.error(e);}
