import {createMeshViewer} from './viewer.js';
const $=id=>document.getElementById(id);
try {
 const viewer=createMeshViewer($('view'));
 const response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build WASM first: ./scripts/build-web.sh');
 const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{}),kernel=instance.exports;let mesh;
 window.haganeDemo={ready:false,setAngle:a=>viewer.setAngle(a),render:()=>viewer.render()};
 function generate(){const radius=Number($('radius').value);const preset=Number($('preset').value);const status=kernel.hagane_generate_preset(preset,radius,0.05);const text=new TextDecoder().decode(new Uint8Array(kernel.memory.buffer,kernel.hagane_output_ptr(),kernel.hagane_output_len()));mesh=JSON.parse(text);if(status)throw Error(mesh.error);viewer.setMesh(mesh);const count=mesh.positions.length/3;const names=['Through bore','Four through bores','L-profile extrusion','Hollow tube','Rotated four-bore part','Rounded profile extrusion','Arc-notch plate with hole','Split planar face','Split curved cap','Split across two holes','Split repeated arc crossings','Split periodic bore','Sew planar patches','Split solid by plane','Intersect convex solids'];const descriptions=['80 × 60 × 24 mm block','80 × 60 × 24 mm · four holes','Concave profile · polygon hole · skew extrusion','Ø60 mm outer · 24 mm height','Rigid B-rep placement · preserved exact bores','80 × 60 × 24 mm · exact line/arc boundary','Concave arc notch · rounded through-hole','Exact cap subdivision · preserved bore and volume','Exact arc rims · subdivided cylinder walls','Three exact cut intervals · shared hole boundaries','Annular cap · two hits per outer and inner arc','Periodic circle · exact rim and cylinder refinement','Independent boundaries · matched shared subdivision','Positive half · exact new closed cap','Box ∩ rotated box · shared exact planar boundaries'];$('part-title').textContent=names[preset];$('part-description').textContent=descriptions[preset];$('radius').disabled=preset===2;document.querySelector('.range-label').children[0].textContent=(preset===9||preset===11||preset===13||preset===14)?'-8 mm':preset===12?'25%':'8 mm';document.querySelector('.range-label').children[1].textContent=(preset===9||preset===11||preset===13||preset===14)?'8 mm':preset===12?'75%':'24 mm';$('radius-title').textContent=preset===3?'Inner radius':preset===5?'Corner radius':preset===6?'Notch radius':preset===7?'Cut offset':preset===8?'Arc cut offset':preset===9?'Hole cut offset':preset===10?'Annular cut offset':preset===11?'Periodic cut offset':preset===12?'Boundary subdivision':preset===13?'Plane offset':preset===14?'Cutter offset':'Bore radius';$('radius-label').value=preset===12?(radius/32*100).toFixed(1)+'%':preset===2?'Fixed profile':((preset===1||preset===4)?radius*0.5:(preset===9||preset===11||preset===13||preset===14)?radius-16:radius).toFixed(1)+' mm';$('topology').textContent=mesh.faces+' faces / '+mesh.edges+' edges';$('volume').textContent=mesh.volume.toLocaleString('en-US',{maximumFractionDigits:1})+' mm³';$('triangles').textContent=(count/3).toLocaleString('en-US');$('status').textContent='✓ Closed B-rep validated in Rust';window.haganeDemo.mesh=mesh;viewer.render();}

 const regenerate=()=>{try{generate();}catch(e){$('status').textContent=e.message;}};
 $('preset').addEventListener('change',regenerate);$('radius').addEventListener('input',regenerate);
 $('wire').addEventListener('change',()=>viewer.wireframe=$('wire').checked);$('spin').addEventListener('change',()=>viewer.autoRotate=$('spin').checked);$('reset').addEventListener('click',()=>viewer.reset());
 generate();window.haganeDemo.ready=true;
}catch(e){$('status').textContent=e.message;console.error(e);}
