import {createMeshViewer} from './viewer.js';
const $=id=>document.getElementById(id);
try{
 const viewer=createMeshViewer($('view')),response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build WASM first.');const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{}),k=instance.exports;
 window.haganeEdgeChamfer={ready:false,data:null,step:null};let acceptedValues=null;
 function result(status){const data=JSON.parse(new TextDecoder().decode(new Uint8Array(k.memory.buffer,k.hagane_output_ptr(),k.hagane_output_len())));if(status)throw Error(data.error??'Chamfer operation rejected.');return data;}
 function render(){const data=window.haganeEdgeChamfer.data;if(!data)return;const part=data[$('part').value],center=[0,1,2].map(axis=>{let lo=Infinity,hi=-Infinity;for(let i=axis;i<part.positions.length;i+=3){lo=Math.min(lo,part.positions[i]);hi=Math.max(hi,part.positions[i]);}return(lo+hi)/2;});viewer.setMesh({positions:part.positions.map((x,i)=>x-center[i%3]),normals:part.normals});const segments=[];for(const points of data.chamfer.bevel_patch.rings)for(let i=0;i<points.length;i++)segments.push([points[i],points[(i+1)%points.length]]);viewer.setSegments(segments.map(segment=>segment.map(p=>p.map((x,i)=>x-center[i]))));$('faces').textContent=part.brep?.faces??part.faces;$('edges').textContent=part.brep?.edges??part.edges;}
 function generate(){const values=['width','depth','height','edge-index','setback'].map(id=>$(id).valueAsNumber);values.push($('angle').valueAsNumber*Math.PI/180,...['tx','ty','tz','linear-tolerance'].map(id=>$(id).valueAsNumber));if(!values.every(Number.isFinite))throw Error('Model fields must contain finite numbers.');k.hagane_edge_chamfer_begin();for(const value of values)if(k.hagane_edge_chamfer_push(value))throw Error('Chamfer input transport rejected.');const data=result(k.hagane_edge_chamfer_finish());window.haganeEdgeChamfer.data=data;acceptedValues=values.slice();window.haganeEdgeChamfer.error=null;window.haganeEdgeChamfer.step=null;window.haganeEdgeChamfer.step_error=null;render();$('source-volume').textContent=data.source.volume.toFixed(3);$('kept-volume').textContent=data.kept.volume.toFixed(3);$('removed-volume').textContent=data.removed.volume.toFixed(3);$('step-status').textContent='Exports the accepted retained solid only.';$('status').textContent='Closed retained and removed B-reps validated · exact planar bevel';}
 $('apply').onclick=()=>{try{generate();}catch(e){window.haganeEdgeChamfer.error=e.message;$('status').textContent='Chamfer rejected: '+e.message+' Accepted geometry and export are preserved.';}};
 $('part').onchange=render;$('wire').onchange=()=>viewer.wireframe=$('wire').checked;$('reset').onclick=()=>viewer.reset();
 $('download-step').onclick=()=>{if(!acceptedValues)return;try{const data=window.haganeEdgeChamfer.data;const step={step:data.step,exact:data.step_exact,units:data.units,schema:data.step_schema};const url=URL.createObjectURL(new Blob([step.step],{type:'application/step'})),link=document.createElement('a');link.href=url;link.download='hagane-edge-chamfer.step';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);window.haganeEdgeChamfer.step=step;window.haganeEdgeChamfer.step_error=null;$('step-status').textContent='Accepted retained B-rep exported · AP214 · mm';}catch(e){window.haganeEdgeChamfer.step_error=e.message;$('step-status').textContent='STEP rejected: '+e.message+' Accepted geometry is preserved.';}};
 generate();window.haganeEdgeChamfer.ready=true;
}catch(e){$('status').textContent=e.message;console.error(e);}
