import {createMeshViewer} from './viewer.js';
const $=id=>document.getElementById(id);
try {
 const viewer=createMeshViewer($('view'));const response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build the WASM module first.');const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{});const k=instance.exports;
 let accepted=null;window.haganePlanarBoolean={ready:false,result:null,accepted:null};
 function display(result){const pieces=result.negative?( $('side').value==='all'?[...result.negative,...result.positive]:result[$('side').value]):(result.kind==='empty'?[]:[result.mesh]);viewer.setMesh({positions:pieces.flatMap(mesh=>mesh.positions),normals:pieces.flatMap(mesh=>mesh.normals)});$('volume').textContent=pieces.reduce((sum,mesh)=>sum+mesh.volume,0).toLocaleString('en-US',{maximumFractionDigits:2})+' mm³';$('parts').textContent=pieces.length;$('status').textContent=result.negative?`Current result · ${pieces.length} independently closed B-rep solids`:result.kind==='empty'?'Current result · empty intersection':'Current result · exact B-rep validated';}
 function rebuild(){const offset=$('offset').valueAsNumber;const mode=Number($('mode').value);$('side').disabled=mode!==2;$('offset-title').textContent=mode===2?'Plane Y offset':'Tool X offset';$('offset-label').textContent=offset+' mm';const status=mode===2?k.hagane_split_components_demo(offset):k.hagane_planar_convex_boolean_demo(mode,offset);const result=JSON.parse(new TextDecoder().decode(new Uint8Array(k.memory.buffer,k.hagane_output_ptr(),k.hagane_output_len())));window.haganePlanarBoolean.result=result;if(status){$('status').textContent='Rejected operation · '+result.error+(accepted?' · showing previous valid result':'');return;}accepted=result;window.haganePlanarBoolean.accepted=result;display(result);}
 $('side').addEventListener('change',()=>{if(accepted&&window.haganePlanarBoolean.result===accepted)display(accepted);});
 $('mode').addEventListener('change',rebuild);$('offset').addEventListener('input',rebuild);$('wire').addEventListener('change',()=>viewer.wireframe=$('wire').checked);$('reset').addEventListener('click',()=>viewer.reset());rebuild();window.haganePlanarBoolean.ready=true;
}catch(error){$('status').textContent=error.message;}
