import {createMeshViewer} from './viewer.js';
const $=id=>document.getElementById(id);
try{
 const viewer=createMeshViewer($('view')),response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build WASM first.');const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{}),k=instance.exports;window.haganePrismRegions={ready:false,data:null,step:null};let accepted=null;
 function result(status){const data=JSON.parse(new TextDecoder().decode(new Uint8Array(k.memory.buffer,k.hagane_output_ptr(),k.hagane_output_len())));if(status)throw Error(data.error??'Split rejected.');return data;}
 function list(data){const part=$('part').value;return Array.isArray(data[part])?data[part]:[data[part]];}
 function components(data){const parts=list(data);$('component').disabled=parts.length===0;$('download-step').disabled=parts.length===0;$('component').replaceChildren(...parts.map((_,i)=>{const o=document.createElement('option');o.value=i;o.textContent='Component '+(i+1);return o;}));}
 function render(data){const part=list(data)[Number($('component').value)];if(!part){viewer.setMesh({positions:[],normals:[]});viewer.setSegments([]);for(const id of['faces','edges','triangles'])$(id).textContent='0';$('status').textContent='Accepted empty '+$('part').value+' · no solid component to export';return;}const center=[0,1,2].map(axis=>{let lo=Infinity,hi=-Infinity;for(let i=axis;i<part.positions.length;i+=3){lo=Math.min(lo,part.positions[i]);hi=Math.max(hi,part.positions[i]);}return(lo+hi)/2;}),segments=[];for(const curve of part.brep.curves){if(curve.kind!=='arc')continue;const[lo,hi]=curve.parameter_range,step=2*Math.acos(Math.max(-1,1-data.display_chord_tolerance/(2*curve.radius))),count=Math.max(1,Math.ceil(Math.abs(hi-lo)/step));if(!Number.isFinite(count)||count>65536)throw Error('Circular boundary display exceeds the segment budget.');const point=t=>curve.frame.origin.map((x,i)=>x+curve.radius*(Math.cos(t)*curve.frame.axes[0][i]+Math.sin(t)*curve.frame.axes[1][i]));let previous=point(lo);for(let i=1;i<=count;i++){const next=point(lo+(hi-lo)*i/count);segments.push([previous,next]);previous=next;}}viewer.setMesh({positions:part.positions.map((x,i)=>x-center[i%3]),normals:part.normals});viewer.setSegments(segments.map(segment=>segment.map(p=>p.map((x,i)=>x-center[i]))));$('faces').textContent=part.brep.faces;$('edges').textContent=part.brep.edges;$('triangles').textContent=part.mesh.triangles.length;}
 function generate(){const values=['width','depth','height','corner-radius','tool-outer-radius','tool-inner-radius','tool-cx','tool-cy'].map(id=>$(id).valueAsNumber);values.push($('tool-phase').valueAsNumber*Math.PI/180,$('angle').valueAsNumber*Math.PI/180,...['tx','ty','tz','linear-tolerance','chord-error'].map(id=>$(id).valueAsNumber));if(!values.every(Number.isFinite))throw Error('Model fields must contain finite numbers.');k.hagane_prism_region_boolean_begin();for(const value of values)if(k.hagane_prism_region_boolean_push(value))throw Error('Arc tool input transport rejected.');const data=result(k.hagane_prism_region_boolean_finish());components(data);render(data);accepted=structuredClone(data);window.haganePrismRegions.data=data;window.haganePrismRegions.error=null;window.haganePrismRegions.step=null;window.haganePrismRegions.step_error=null;$('source-volume').textContent=data.source.volume.toFixed(3);$('difference-volume').textContent=data.difference.reduce((s,b)=>s+b.volume,0).toFixed(3);$('intersection-volume').textContent=data.intersection.reduce((s,b)=>s+b.volume,0).toFixed(3);$('union-volume').textContent=data.union.reduce((s,b)=>s+b.volume,0).toFixed(3);$('step-status').textContent='Retained planes, cylinders and bounded circular arcs.';$('status').textContent='Accepted difference: '+data.difference.length+' solid(s) · intersection: '+data.intersection.length+' solid(s) · union: '+data.union.length+' solid(s) · exact closed B-reps';}
 $('apply').onclick=()=>{try{generate();}catch(e){window.haganePrismRegions.error=e.message;$('status').textContent='Operation rejected: '+e.message+' Accepted solid and STEP export are preserved.';}};$('part').onchange=()=>{if(accepted){components(accepted);render(accepted);}};$('component').onchange=()=>{if(accepted)render(accepted);};$('wire').onchange=()=>viewer.wireframe=$('wire').checked;$('reset').onclick=()=>viewer.reset();
 $('download-step').onclick=()=>{const data=accepted;if(!data)return;try{const part=$('part').value,component=Number($('component').value),step={step:Array.isArray(data[part])?data[part+'_steps'][component]:data[part+'_step'],exact:data.step_exact,units:data.units,schema:data.step_schema,part,component};const url=URL.createObjectURL(new Blob([step.step],{type:'application/step'})),link=document.createElement('a');link.href=url;link.download='hagane-prism-regions-'+part+'-'+component+'.step';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);window.haganePrismRegions.step=step;window.haganePrismRegions.step_error=null;$('step-status').textContent='Accepted '+part+' B-rep exported · AP214 · mm';}catch(e){window.haganePrismRegions.step_error=e.message;$('step-status').textContent='STEP rejected: '+e.message+' Accepted solid preserved.';}};
 generate();window.haganePrismRegions.ready=true;
}catch(e){$('status').textContent=e.message;console.error(e);}
