import {createMeshViewer} from './viewer.js';
const $=id=>document.getElementById(id),MAX_BYTES=1024*1024;
try{
 const viewer=createMeshViewer($('view')),response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build WASM first.');const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{}),k=instance.exports,state=window.haganeStepBounded={ready:false,data:null,step:null};
 function result(status){const data=JSON.parse(new TextDecoder().decode(new Uint8Array(k.memory.buffer,k.hagane_output_ptr(),k.hagane_output_len())));if(status)throw Error(data.error??'STEP rejected.');return data;}
 function render(data){const part=data.solid,center=[0,1,2].map(axis=>{let lo=Infinity,hi=-Infinity;for(let i=axis;i<part.positions.length;i+=3){lo=Math.min(lo,part.positions[i]);hi=Math.max(hi,part.positions[i]);}return(lo+hi)/2;}),segments=[];for(const curve of part.brep.curves){if(curve.kind!=='arc')continue;const[lo,hi]=curve.parameter_range,step=2*Math.acos(Math.max(-1,1-data.display_chord_tolerance/(2*curve.radius))),count=Math.max(1,Math.ceil(Math.abs(hi-lo)/step));if(!Number.isFinite(count)||count>65536)throw Error('Circular boundary display exceeds its segment budget.');const point=t=>curve.frame.origin.map((x,i)=>x+curve.radius*(Math.cos(t)*curve.frame.axes[0][i]+Math.sin(t)*curve.frame.axes[1][i]));let previous=point(lo);for(let i=1;i<=count;i++){const next=point(lo+(hi-lo)*i/count);segments.push([previous,next]);previous=next;}}viewer.setMesh({positions:part.positions.map((x,i)=>x-center[i%3]),normals:part.normals});viewer.setSegments(segments.map(segment=>segment.map(p=>p.map((x,i)=>x-center[i]))));}
 function accept(text){const bytes=new TextEncoder().encode(text);if(bytes.length>MAX_BYTES)throw Error('STEP input exceeds 1 MiB.');k.hagane_step_bounded_begin();for(const byte of bytes)if(k.hagane_step_bounded_push_byte(byte))throw Error('STEP input transport rejected.');const data=result(k.hagane_step_bounded_finish());acceptReport(text,data);}
 function acceptReport(text,data){render(data);state.data=data;state.error=null;state.step=null;$('volume').textContent=data.solid.volume.toFixed(3);$('faces').textContent=data.solid.brep.faces;$('edges').textContent=data.solid.brep.edges;$('triangles').textContent=data.solid.mesh.triangles.length;$('linear-tolerance').value=data.linear_tolerance;$('chord-error').value=data.display_chord_tolerance;$('step-file').value='';$('step-text').value=text;$('status').textContent='Accepted bounded analytic STEP · closed B-rep · checked display error';$('step-status').textContent='Canonical geometry export; original file bytes need not match.';}
 function reject(e){state.error=e.message;$('status').textContent='STEP rejected: '+e.message+' Accepted solid and export are preserved.';}
 function sample(values=[80,60,20,0,0,0,0,1e-6,.1,4,8,3,9,3,10,3,11,3]){k.hagane_edge_fillet_begin();for(const value of values)if(k.hagane_edge_fillet_push(value))throw Error('Sample input rejected.');accept(result(k.hagane_edge_fillet_finish()).step);}
 state.loadSample=sample;state.loadOpeningsSample=()=>{const sample=result(k.hagane_step_bounded_openings_sample());acceptReport(sample.input_step,sample.report);};$('sample-openings').onclick=()=>{try{state.loadOpeningsSample();}catch(e){reject(e);}};$('sample').onclick=()=>{try{sample();}catch(e){reject(e);}};$('import-step').onclick=async()=>{try{let text=$('step-text').value;const file=$('step-file').files[0];if(file){if(file.size>MAX_BYTES)throw Error('STEP input exceeds 1 MiB.');const bytes=await file.arrayBuffer();try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw Error('STEP file must contain valid UTF-8.');}}accept(text);}catch(e){reject(e);}};$('wire').onchange=()=>viewer.wireframe=$('wire').checked;$('reset').onclick=()=>viewer.reset();$('download-step').onclick=()=>{if(!state.data)return;const url=URL.createObjectURL(new Blob([state.data.step],{type:'application/step'})),link=document.createElement('a');link.href=url;link.download='hagane-bounded-analytic.step';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);state.step=state.data.step;$('step-status').textContent='Accepted analytic B-rep exported · AP214 · mm';};sample();state.ready=true;
}catch(e){$('status').textContent=e.message;console.error(e);}
