// Shared display-only WebGL viewer. All geometry/normal evaluation lives in Rust.
export function createMeshViewer(canvas,{doubleSided=false}={}) {
 const gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});
 if(!gl)throw Error('WebGL is unavailable in this browser.');
 let yaw=0.65,elevation=0.82,distance=205,count=0,dragging=false,last=[0,0],wire=false,spin=false,markerCount=0;
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
 const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,`
attribute vec3 position;attribute vec3 normal;uniform vec3 right;uniform vec3 up;uniform vec3 back;uniform float distance;uniform mat4 projection;varying vec3 n;
void main(){n=normal;vec3 q=vec3(dot(position,right),dot(position,up),dot(position,back)-distance);gl_Position=projection*vec4(q,1.0);gl_PointSize=7.0;}`));
 gl.attachShader(p,shader(gl.FRAGMENT_SHADER,`
precision highp float;varying vec3 n;uniform bool lines;uniform bool doubleSided;uniform vec3 lineColor;
void main(){if(lines){gl_FragColor=vec4(lineColor,1.0);return;}vec3 N=normalize(n);if(doubleSided&&!gl_FrontFacing)N=-N;float light=max(dot(N,normalize(vec3(-0.5,-0.7,1.0))),0.0);float rim=max(dot(N,normalize(vec3(0.7,0.5,0.3))),0.0);vec3 color=vec3(0.66,0.73,0.47)*(0.28+0.68*light)+vec3(0.20,0.27,0.25)*rim;gl_FragColor=vec4(color,1.0);}`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.useProgram(p);gl.enable(gl.DEPTH_TEST);if(!doubleSided)gl.enable(gl.CULL_FACE);
 const locations=Object.fromEntries(['right','up','back','distance','projection','lines','doubleSided','lineColor'].map(k=>[k,gl.getUniformLocation(p,k)]));gl.uniform1i(locations.doubleSided,doubleSided);
 const buffers=Object.fromEntries(['positions','normals','linePositions','lineNormals','marker','markerNormals'].map(k=>[k,gl.createBuffer()]));
 function bind(buffer,attribute,data){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);if(data)gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);const loc=gl.getAttribLocation(p,attribute);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);}
 function render(){const dpr=Math.min(devicePixelRatio,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(!w||!h)return;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const back=[Math.sin(yaw)*Math.cos(elevation),-Math.cos(yaw)*Math.cos(elevation),Math.sin(elevation)],right=[Math.cos(yaw),Math.sin(yaw),0],up=[-Math.sin(yaw)*Math.sin(elevation),Math.cos(yaw)*Math.sin(elevation),Math.cos(elevation)];gl.uniform3fv(locations.back,back);gl.uniform3fv(locations.right,right);gl.uniform3fv(locations.up,up);gl.uniform1f(locations.distance,distance);const f=1/Math.tan(0.65/2),near=1,far=1000;gl.uniformMatrix4fv(locations.projection,false,new Float32Array([f/(w/h),0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]));bind(buffers.positions,'position');bind(buffers.normals,'normal');gl.uniform1i(locations.lines,0);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);gl.drawArrays(gl.TRIANGLES,0,count);gl.disable(gl.POLYGON_OFFSET_FILL);gl.uniform1i(locations.lines,1);if(wire){gl.uniform3fv(locations.lineColor,[0.12,0.17,0.12]);bind(buffers.linePositions,'position');bind(buffers.lineNormals,'normal');gl.drawArrays(gl.LINES,0,count*2);}if(markerCount){gl.depthFunc(gl.LEQUAL);gl.uniform3fv(locations.lineColor,[0.4,0.9,0.85]);bind(buffers.marker,'position');bind(buffers.markerNormals,'normal');gl.drawArrays(gl.LINES,0,markerCount);gl.drawArrays(gl.POINTS,0,1);gl.depthFunc(gl.LESS);}}
 function setMesh(mesh){if(mesh.positions.length!==mesh.normals.length||mesh.positions.length%9!==0)throw Error('Invalid display mesh.');count=mesh.positions.length/3;bind(buffers.positions,'position',mesh.positions);bind(buffers.normals,'normal',mesh.normals);const lines=[],normals=[];for(let i=0;i<count;i+=3){for(const [a,b] of [[0,1],[1,2],[2,0]]){lines.push(...mesh.positions.slice((i+a)*3,(i+a+1)*3),...mesh.positions.slice((i+b)*3,(i+b+1)*3));normals.push(...mesh.normals.slice((i+a)*3,(i+a+1)*3),...mesh.normals.slice((i+b)*3,(i+b+1)*3));}}bind(buffers.linePositions,'position',lines);bind(buffers.lineNormals,'normal',normals);render();}
 function setMarker(point,normal){markerCount=point?2:0;if(point){bind(buffers.marker,'position',[...point,...point.map((v,i)=>v+normal[i]*14)]);bind(buffers.markerNormals,'normal',[...normal,...normal]);}render();}
 function setSegments(segments){const positions=segments.flat(2);markerCount=positions.length/3;bind(buffers.marker,'position',positions);bind(buffers.markerNormals,'normal',new Array(positions.length).fill(0));render();}
 const api={setMesh,setMarker,setSegments,render,setAngle(a){yaw=a;render();},reset(){yaw=0.65;elevation=0.82;distance=205;render();},set wireframe(value){wire=Boolean(value);render();},set autoRotate(value){spin=Boolean(value);}};
 canvas.addEventListener('pointerdown',e=>{dragging=true;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw+=(e.clientX-last[0])*0.008;elevation=Math.max(-1.35,Math.min(1.35,elevation+(e.clientY-last[1])*0.006));last=[e.clientX,e.clientY];render();});canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(120,Math.min(350,distance*Math.exp(e.deltaY*0.001)));render();},{passive:false});canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')yaw-=0.1;else if(e.key==='ArrowRight')yaw+=0.1;else if(e.key==='ArrowUp')elevation=Math.min(1.35,elevation+0.1);else if(e.key==='ArrowDown')elevation=Math.max(-1.35,elevation-0.1);else if(e.key==='+')distance=Math.max(120,distance-10);else if(e.key==='-')distance=Math.min(350,distance+10);else return;e.preventDefault();render();});new ResizeObserver(render).observe(canvas);let previous=performance.now();function frame(now){if(spin){yaw+=(now-previous)*0.00025;render();}previous=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);return api;
}
