import {createMeshViewer} from './viewer.js';
const $=id=>document.getElementById(id);
try {
 const viewer=createMeshViewer($('view'));
 const response=await fetch('hagane.wasm');if(!response.ok)throw Error('Build the WASM module first.');
 const {instance}=await WebAssembly.instantiate(await response.arrayBuffer(),{}),k=instance.exports;
 const defaultDocument={schema_version:1,units:'mm',tolerance:{linear:1e-8,angular:1e-10,relative:1e-12},operations:[{kind:'box',id:'box-1',size:[80,60,24]},{kind:'bore',id:'bore-1',input:'box-1',mode:'blind',center:[0,0],radius:14,depth:16}]};
 let draft=structuredClone(defaultDocument);
 let lastValid=null, selected=1, current=null;
 const undoStack=[],redoStack=[];const maxUndo=64;
 const storageKey='hagane.workflow.autosave.v1';let savedText=null,storageBlocked=false,starting=true;
 function storageMessage(text){$('storage-state').textContent=text;}
 function saveLocal(explicit=false){if(starting||!lastValid)return;try{const existing=localStorage.getItem(storageKey);if(!explicit&&(storageBlocked||existing!==savedText)){storageBlocked=true;storageMessage('Local save paused: saved data changed or could not be restored. Use Save this tab locally to replace it.');return;}const text=JSON.stringify({storage_version:1,document:lastValid.document,selected});if(new TextEncoder().encode(text).length>66560)throw Error('Saved model exceeds the local size limit.');localStorage.setItem(storageKey,text);savedText=text;storageBlocked=false;storageMessage('Current validated model saved locally in this browser.');}catch(error){storageMessage('Local save unavailable: '+error.message+'. Download the editable model to keep a copy.');}}
 $('save-tab').addEventListener('click',()=>{if(!window.haganeWorkflow.report?.ok){storageMessage('Correct or discard the rejected edit before saving this tab.');return;}saveLocal(true);});
 window.addEventListener('storage',event=>{if((event.key===storageKey||event.key===null)&&event.newValue!==savedText){storageBlocked=true;storageMessage('Local save paused: another tab changed the saved model. This tab keeps its current part.');}});
 window.haganeWorkflow={ready:false,report:null,lastValid:null};
 function updateUndo(){const rejected=window.haganeWorkflow.report?.ok===false;$('undo').disabled=!current||(!rejected&&!undoStack.length);$('redo').disabled=rejected||!redoStack.length;$('edit-history-state').textContent=`${undoStack.length} undo · ${redoStack.length} redo${rejected?' · Undo discards rejected edit':''}`;}
 function remember(document){const snapshot={text:JSON.stringify(document),selected};if(current&&current.text!==snapshot.text){undoStack.push(current);if(undoStack.length>maxUndo)undoStack.shift();redoStack.length=0;}current=snapshot;}
 function navigate(direction){if(!current)return;const rejected=window.haganeWorkflow.report?.ok===false;if(direction==='undo'&&rejected){selected=current.selected;process(current.text,false,false);updateUndo();return;}if(rejected)return;const source=direction==='undo'?undoStack:redoStack,target=direction==='undo'?redoStack:undoStack;if(!source.length)return;const snapshot=source.at(-1),previous=current,oldSelected=selected;selected=snapshot.selected;const report=process(snapshot.text,false,false);if(report.ok){source.pop();target.push(previous);current=snapshot;saveLocal();}else{selected=oldSelected;}updateUndo();}
 $('undo').addEventListener('click',()=>navigate('undo'));$('redo').addEventListener('click',()=>navigate('redo'));
 document.addEventListener('keydown',event=>{if(!(event.ctrlKey||event.metaKey)||event.altKey||['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)||event.target.isContentEditable)return;const key=event.key.toLowerCase();if(key==='z'||key==='y'){event.preventDefault();navigate(key==='y'||event.shiftKey?'redo':'undo');}});
 function evaluate(text){k.hagane_workflow_begin();for(const byte of new TextEncoder().encode(text)){if(k.hagane_workflow_push_byte(byte))break;}const status=k.hagane_workflow_finish_incremental();const result=JSON.parse(new TextDecoder().decode(new Uint8Array(k.memory.buffer,k.hagane_output_ptr(),k.hagane_output_len())));if(status)throw Error(result.error??'Model transport failed');return result;}
 function history(document,failed){$('selected-bore').replaceChildren();document.operations.slice(1).forEach((op,i)=>{const option=window.document.createElement('option');option.value=i+1;option.textContent=op.id;$('selected-bore').append(option);});$('selected-bore').value=selected;$('remove-bore').disabled=document.operations.length<2;$('history').replaceChildren();for(const op of document.operations){const item=window.document.createElement('li');item.textContent=`${op.id} · ${op.kind}${op.mode?' / '+op.mode:''}${op.id===failed?' · rejected':''}`;$('history').append(item);}}
 function fill(document){const box=document.operations[0];selected=Math.min(Math.max(1,selected),Math.max(1,document.operations.length-1));const bore=document.operations[selected];['width','length','height'].forEach((id,i)=>$(id).value=box.size[i]);$('mode').value=bore?.mode??'box_only';if(bore){$('radius').value=bore.radius;$('cx').value=bore.center[0];$('cy').value=bore.center[1];if(bore.depth!=null)$('depth').value=bore.depth;}disable();}
 function disable(){const mode=$('mode').value;for(const id of ['radius','cx','cy'])$(id).disabled=mode==='box_only';$('depth').disabled=mode!=='blind';}
 function rebuild(text,importing=false,record=true){$('transport').textContent='';
  const report=evaluate(text);window.haganeWorkflow.report=report;$('save').disabled=!report.ok;
  if(report.ok){draft=report.document;lastValid=report;window.haganeWorkflow.lastValid=report;viewer.setMesh(report.mesh);viewer.setSegments([]);$('result-state').textContent='Current edit · exact B-rep validated';$('diagnostic').textContent='';const stats=report.rebuild;$('rebuild-stats').textContent=`${stats.reused_operations} operations reused · ${stats.rebuilt_operations} rebuilt${stats.rebuilt_operation_ids.length?' · '+stats.rebuilt_operation_ids.join(', '):''}`;$('volume').textContent=report.mesh.volume.toLocaleString('en-US',{maximumFractionDigits:1})+' mm³';$('topology').textContent=`${report.mesh.faces} faces / ${report.mesh.edges} edges`;$('document').value=JSON.stringify(draft,null,2);fill(draft);history(draft,null);if(record){remember(draft);saveLocal();}}
  else{$('rebuild-stats').textContent='Edit rejected · accepted history cache retained';const d=report.diagnostic;$('result-state').textContent=lastValid?'Rejected edit · showing previous valid result':'Rejected edit · no valid result';let text=`${d.operation_id??'Document'} · ${d.code}: ${d.message}`;if(d.measured_clearance!=null)text+=` Clearance ${d.measured_clearance.toPrecision(6)} mm; required > ${d.required_clearance.toPrecision(6)} mm.`;if(d.suggestion)text+=' '+d.suggestion;$('diagnostic').textContent=text;viewer.setSegments(report.candidate_segments??[]);history(report.attempted_document??draft,d.operation_id);}
  updateUndo();viewer.render();return report;
 }
 function process(text,importing=false,record=true){try{return rebuild(text,importing,record);}catch(e){$('save').disabled=true;$('result-state').textContent=lastValid?'Rejected edit · showing previous valid result':'Rejected edit · no valid result';$('transport').textContent=e.message;$('rebuild-stats').textContent='No accepted rebuild';window.haganeWorkflow.report={ok:false,diagnostic:{code:'transport_failed',message:e.message}};updateUndo();return window.haganeWorkflow.report;}}
 function fromControls(){const model=structuredClone(draft);model.operations[0].size=['width','length','height'].map(id=>$(id).valueAsNumber);const mode=$('mode').value;if(mode==='box_only'){model.operations.splice(selected,1);}else{const previous=model.operations[selected];const bore={kind:'bore',id:previous?.id??'bore-1',input:model.operations[selected-1]?.id??model.operations[0].id,mode,center:[$('cx').valueAsNumber,$('cy').valueAsNumber],radius:$('radius').valueAsNumber};if(mode==='blind')bore.depth=$('depth').valueAsNumber;model.operations[selected]=bore;}for(let i=1;i<model.operations.length;i++)model.operations[i].input=model.operations[i-1].id;return model;}
 $('selected-bore').addEventListener('change',()=>{selected=Number($('selected-bore').value);fill(draft);if(current&&window.haganeWorkflow.report?.ok){current.selected=selected;saveLocal();}});
 $('add-bore').addEventListener('click',()=>{let n=1;while(draft.operations.some(op=>op.id===`bore-${n}`))n++;draft.operations.push({kind:'bore',id:`bore-${n}`,input:draft.operations.at(-1).id,mode:'through',center:[24,0],radius:4});selected=draft.operations.length-1;fill(draft);$('document').value=JSON.stringify(draft,null,2);process($('document').value);});
 $('remove-bore').addEventListener('click',()=>{draft.operations.splice(selected,1);for(let i=1;i<draft.operations.length;i++)draft.operations[i].input=draft.operations[i-1].id;selected=Math.min(selected,Math.max(1,draft.operations.length-1));fill(draft);process(JSON.stringify(draft));});

 for(const id of ['width','length','height','radius','depth','cx','cy','mode'])$(id).addEventListener(id==='mode'?'change':'input',()=>{disable();const document=fromControls();draft=document;$('document').value=JSON.stringify(document,null,2);process($('document').value);});
 $('load').addEventListener('click',()=>{try{process($('document').value,true);}catch(e){$('transport').textContent=e.message;}});
 $('save').addEventListener('click',()=>{if(!window.haganeWorkflow.report?.ok)return;const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='hagane-model.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 $('file').addEventListener('change',async()=>{const file=$('file').files[0];if(!file)return;if(file.size>65536){$('transport').textContent='Model file exceeds 64 KiB.';return;}try{$('document').value=await file.text();process($('document').value,true);$('transport').textContent='';}catch(e){$('transport').textContent=e.message;}});
 $('wire').addEventListener('change',()=>viewer.wireframe=$('wire').checked);$('reset').addEventListener('click',()=>viewer.reset());
 let restored=false,restoreIssue=null;
 try{savedText=localStorage.getItem(storageKey);if(savedText!==null){if(new TextEncoder().encode(savedText).length>66560)throw Error('Saved data exceeds the local size limit');const saved=JSON.parse(savedText);if(!saved||Array.isArray(saved)||Object.keys(saved).sort().join(',')!=='document,selected,storage_version'||saved.storage_version!==1||!Number.isInteger(saved.selected)||saved.selected<1||saved.selected>256)throw Error('Unsupported or malformed saved workspace');selected=saved.selected;const report=process(JSON.stringify(saved.document));if(!report.ok)throw Error(report.diagnostic.message);if(selected!==saved.selected)throw Error('Saved bore selection is outside the model');restored=true;}}
 catch(error){restoreIssue=error.message;storageBlocked=true;}
 if(!restored){selected=1;current=null;undoStack.length=0;redoStack.length=0;draft=structuredClone(defaultDocument);fill(draft);rebuild(JSON.stringify(draft));}
 starting=false;
 if(restoreIssue)storageMessage('Saved model rejected or unavailable: '+restoreIssue+'. Showing the default part; saved data was not replaced.');
 else if(restored)storageMessage('Restored saved model · exact B-rep validated. Undo history starts here.');
 else saveLocal();
 window.haganeWorkflow.ready=true;
}catch(e){$('result-state').textContent=e.message;console.error(e);}
